
name: Tests
  
on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

      
  workflow_dispatch:

    
jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: | 
        echo Installing cell_counter module
        pip install .
        echo Running tests...
        python3 CI_tests.py

